### ISSUE TITLE
有兴趣做3球+的吗

### ISSUE THREAD

**Issue by Saplonily** [qwertycxz/ADOFAI-2PlanetsTo3Planets#1]
rt(

**Comment by qwertycxz** [comment]
我看看……

**Comment by qwertycxz** [comment]
增添了一个球数选择的功能,虽说主要是为了3球转2球的,但也尽量为3球+做了适配
(话说3球+是咋做到的……)

**Comment by Saplonily** [comment]
> 增添了一个球数选择的功能,虽说主要是为了3球转2球的,但也尽量为3球+做了适配 (话说3球+是咋做到的……)

游戏三球逻辑那里有个if(num > 3) num = 3的条件限制最大为3球,把这个逻辑删了就可以了

具体我就不剧透了

**Comment by qwertycxz** [comment]
找到这段代码了,也找到官方关于3球+的恳求了……怪不得没人发布此类的mod
issue我关了,有啥问题再开个新的issue就好
